// All interface text. Simple, everyday Hindi — not formal financial Hindi.
// To rename the app, change APP_NAME only.

export const APP_NAME = { en: "SANGYAN Decision Guard", hi: "संज्ञान डिसीज़न गार्ड" };
export const APP_SHORT = { en: "SANGYAN", hi: "संज्ञान" };

const en = {
  tagline: "Before you act, let's check.",
  login_title: "Log in",
  username: "Login ID / username",
  password: "PIN / password",
  new_user: "New here?",
  new_user_sub: "Create your own account with your name and a 4-digit PIN. It starts empty — no demo data.",
  create_account: "Create account",
  signup_title: "Create your account",
  signup_sub: "Just your name and a 4-digit PIN. No phone number, email, Aadhaar or bank details.",
  your_name: "Your name",
  choose_pin: "Choose a 4-digit PIN",
  confirm_pin: "Type the PIN again",
  signup_need_name: "Please enter your name.",
  signup_need_pin: "The PIN must be exactly 4 digits.",
  signup_pin_mismatch: "The two PINs don't match.",
  signup_done_title: "Account created",
  signup_done_sub: "Use this Login ID and your PIN to log in next time, on any phone.",
  your_login_id: "Your Login ID",
  copy_id: "Copy Login ID",
  copied: "Copied",
  signup_write_down: "Write down your Login ID. We don't store accounts, so it cannot be recovered if you forget it or your PIN.",
  continue: "Continue",
  slow_down: "Too many tries. Please wait a minute.",
  signup_privacy: "Your checks and trades stay on this phone. We don't keep a list of users.",
  login_btn: "Log in",
  login_fail: "Wrong username or password.",
  demo_accounts: "Demo accounts (for judges)",
  use_this: "Use this account",
  privacy_line: "We never ask for your broker login, bank details or Aadhaar. Your checks stay on this phone.",
  nav_home: "Home",
  nav_history: "History",
  nav_learn: "Learn",
  nav_profile: "Profile",
  nav_ask: "Ask",
  tab_alerts: "Alerts",
  tab_words: "Words",
  all: "All",
  alerts_sub: "Real fraud cases from official sources and trusted news, and what the government has put in place. Learn the tricks before someone tries them on you.",
  alerts_govt: "What the government is doing",
  alerts_recent: "Recent fraud alerts",
  alerts_none: "Live alerts couldn't be loaded right now. The government measures above are always available.",
  alerts_note: "Headlines come from SEBI and known news outlets, updated about every hour. Open the source to read the full story.",
  alert_official: "Official",
  alert_news: "News",
  alert_govt: "Govt action",
  alert_translated: "translated",
  alert_read: "Read source",
  alert_open_official: "Open official site",
  home_alert_title: "Fraud alert",
  home_alert_more: "See all alerts",
  related_alerts: "Similar frauds in the news",
  call_1930: "Call 1930",
  ask_title: "Ask Saathi",
  ask_sub: "Ask how to use the app, what a word means, or how scams work. Type or speak, in Hindi or English.",
  ask_rule: "Saathi explains things. It never tells you to buy or sell, and never predicts prices.",
  ask_hello: "Namaste! I'm Saathi. What would you like to know?",
  ask_try: "Tap a question below or type your own.",
  ask_placeholder: "Type your question…",
  ask_send: "Send",
  ask_thinking: "Saathi is typing…",
  ask_clear: "Clear chat",
  ask_src_ai: "AI answer, from the app's help",
  ask_src_rule: "Fixed safety rule",
  ask_src_faq: "From the app's help",
  ask_src_lookup: "SEBI registry search",
  hello: "Namaste",
  home_ask: "Thinking of buying or selling a share?",
  home_ask_sub: "Take 2 minutes to check the tip, who sent it, and your own recent trades.",
  check_btn: "Check a decision",
  upload_btn: "Upload screenshot",
  speak_btn: "Speak",
  recent_checks: "Recent checks",
  no_checks: "No checks yet. Your checks will appear here.",
  paused_count: "times you paused before acting",
  waiting_title: "You chose to wait",
  waiting_left: "left",
  waiting_done: "Wait is over — look at it again with a fresh mind.",
  followup_title: "How did it go?",
  followup_sub: "A week ago you checked this. Looking back helps you learn.",
  followup_glad: "Glad I checked",
  followup_neutral: "Not sure",
  followup_regret: "Wish I had waited",
  followup_thanks: "Thanks — noted in your history.",
  step1: "What did you hear?",
  step2: "What are you planning?",
  step3: "Why this trade?",
  step_of: "Step",
  where_from: "Where did the tip come from?",
  src_youtube: "YouTube",
  src_whatsapp: "WhatsApp",
  src_telegram: "Telegram",
  src_instagram: "Instagram",
  src_friend: "Friend / family",
  src_news: "News",
  src_influencer: "Finfluencer",
  src_sms: "SMS / call",
  src_other: "Other",
  know_sender: "Do you personally know who sent it?",
  yes: "Yes",
  no: "No",
  not_sure: "Not sure",
  paste_label: "Paste the message (or type what was said)",
  paste_ph: "e.g. \"Buy Tata Motors now, 40% guaranteed return in 1 month!\"",
  link_label: "Link (YouTube / website / group) — optional",
  link_ph: "https://…",
  views_label: "Views / followers (if you can see it) — optional",
  add_screenshot: "Add screenshot",
  reading_screenshot: "Reading text from screenshot…",
  screenshot_done: "Text added from screenshot. Please check it.",
  screenshot_fail: "Could not read the screenshot. Please type the main lines.",
  speak_hint: "Tap and speak",
  listening: "Listening… tap to stop",
  voice_unsupported: "Voice input isn't available in this browser.",
  which_share: "Which company?",
  search_company: "Search company name",
  search_company_all: "Search any NSE / BSE company (name or symbol)",
  popular_stocks: "Popular",
  searching: "Searching…",
  no_company_found: "No company found. Check the spelling, or add it as \"Other company\".",
  other_company: "Other company (not in list)",
  other_company_name: "Company name",
  buy: "Buy",
  sell: "Sell",
  how_many: "How many shares?",
  amount: "About how much money? (₹)",
  amount_auto: "We filled this using the latest price. You can change it.",
  why_q: "Why are you thinking of this trade? (tap all that apply)",
  r_recommended: "Someone recommended it",
  r_news: "I saw news",
  r_recover_loss: "To recover a recent loss",
  r_friends_buying: "Friends / everyone is buying",
  r_price_falling: "Price fell, buying cheap",
  r_own_research: "My own research",
  r_fear_missing: "Don't want to miss out",
  reason_more: "Anything else? (optional)",
  next: "Next",
  back: "Back",
  check_now: "Check now",
  checking: "Checking…",
  checking_steps: "Reading the message · Checking SEBI records · Looking at company facts · Looking at your recent trades",
  error_generic: "Something went wrong. Please try again.",
  error_offline: "You seem to be offline. Connect to the internet and try again.",
  need_company: "Please choose a company.",
  need_qty: "Please enter the number of shares.",
  verdict_green: "No major warning signs",
  verdict_orange: "Review before you decide",
  verdict_red: "Pause",
  green_note: "This does not mean it is a good investment. It only means we did not find major warning signs in what we checked.",
  not_prediction: "These are warning signs, not a prediction of what the share will do. The decision is yours.",
  we_checked: "We checked",
  things: "things",
  top_three: "Most important to check",
  tip_age_q: "When did you get or see this tip?",
  tip_age_today: "Today",
  tip_age_week: "This week",
  tip_age_month: "This month",
  tip_age_older: "Older",
  tip_age_unknown: "Not sure",
  fresh_published: "Published",
  fresh_fresh: "recent",
  fresh_weeks: "a few weeks old",
  fresh_months: "months old",
  fresh_old: "very old",
  source_name_label: "Name of the person or channel (optional)",
  source_name_ph: "e.g. person's name or channel name",
  source_name_help: "We'll look this name up in SEBI's lists of registered advisers and analysts.",
  video_inside: "Inside the video",
  video_watched_all: "AI watched the video (speech + on-screen text)",
  video_not_watched_short: "We could not watch inside this video, so only its title and description were checked. Reason:",
  video_quota_tip: "Tip: the free AI plan allows a limited amount of video per minute and per day. Wait a minute and check again — the same video is remembered once it works.",
  video_nokey_tip: "Tip: add GEMINI_API_KEY to the .env.local file in the app folder and restart the app.",
  video_watched: "AI watched the first 15 minutes (speech + on-screen text)",
  video_speaker: "Speaker",
  video_no_claims: "No specific claims or calls were found in the part we watched.",
  video_regs: "SEBI numbers shown",
  video_links: "Links / groups / UPI mentioned",
  video_disclaimer_yes: "A risk disclaimer was said or shown",
  video_disclaimer_no: "No risk disclaimer was said or shown",
  video_ai_note: "Found by AI — tap a time to check it yourself in the video.",
  video_not_watched: "We could not watch inside this video, so only its title and description were checked. See \"What we could not check\" below for the reason.",
  checking_video: "Watching the YouTube video (first 10 minutes) — this can take up to a minute.",
  sec_message: "About the message",
  sec_source: "About who sent it",
  sec_behaviour: "About your recent trades",
  sec_company: "About the company (facts only)",
  sec_ok: "What looked fine",
  sec_not_checked: "What we could not check",
  why_matters: "Why this matters",
  what_found: "What we found",
  what_check: "What to check",
  explain_term: "What does this mean?",
  ai_summary: "What the content claims (AI summary)",
  ai_note: "AI helped read the content. The colour above comes from fixed rules, not from AI.",
  read_aloud: "Read aloud",
  stop_reading: "Stop",
  share_family: "Share with family",
  wait_15: "Wait 15 minutes",
  wait_day: "Sleep on it (24 hours)",
  write_journal: "Write down my reasons",
  i_decided: "I've decided",
  decided_go: "I'll go ahead",
  decided_skip: "I'll skip it",
  decision_saved: "Saved. Whatever you decide, you checked first — well done.",
  journal_title: "Your decision notes",
  journal_sub: "Writing your reasons slows down a hurried decision. Speak or type.",
  jq1: "Why do you want to make this trade?",
  jq2: "What evidence supports it?",
  jq3: "What would make you change your mind?",
  jq4: "If the trade goes against you, how much can you afford to lose?",
  journal_save: "Save notes",
  journal_saved: "Notes saved.",
  history_title: "Your checks",
  learn_title: "Learn",
  learn_sub: "Simple meanings of common words, and how common scams work.",
  learn_terms: "Words explained",
  learn_scams: "Common scams",
  how_it_works: "How it works",
  how_to_spot: "How to spot it",
  help_title: "Need help? Lost money?",
  profile_title: "Profile",
  my_trades: "Your past trades",
  my_trades_sub: "Used only to spot habits like loss-chasing. Demo trades come with the account; trades you add stay on this phone.",
  add_trade: "Add a past trade",
  import_csv: "Import tradebook (CSV)",
  import_done: "trades imported",
  import_fail: "Could not read any trades from this file. Try the sample file format below.",
  import_excel: "This is an Excel file. Open it in Excel → File → Save As → \"CSV (Comma delimited)\", then import the .csv file.",
  import_missing: "Could not find these columns in the file:",
  col_symbol: "stock name/symbol",
  col_date: "date",
  col_qty: "quantity",
  col_price: "price (or total value)",
  import_skipped: "rows skipped (missing date/quantity/price)",
  import_dupes: "already imported",
  import_help: "CSV with columns: date, stock, buy/sell, quantity, price (profit/loss optional). Most broker tradebooks work.",
  import_sample: "Download sample CSV",
  profit_loss: "Profit / loss (₹)",
  date: "Date",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  logout: "Log out",
  language: "Language",
  data_note: "Your data: checks and added trades are stored only in this browser. We don't connect to your broker or bank.",
  sebi_list_note: "SEBI registry list loaded",
  ai_on: "AI reading: on",
  ai_off: "AI reading: off (rules only)",
  install_app: "Add to home screen",
  wa_share_text: "I checked this tip with SANGYAN Decision Guard before acting:",
  open_result: "Open",
  decision_went: "Went ahead",
  decision_skipped: "Skipped",
  decision_waiting: "Waiting",
  usual_trade: "Usual trade size",
  trades_7d: "Trades in last 7 days",
  total_trades: "Trades on record",
  close: "Close",
  advice_reply_title: "We don't give buy/sell advice",
  share_received: "Shared message received. Add the details below.",
  disclaimer_footer: "Not investment advice. This tool checks for warning signs; it never tells you to buy, sell or hold.",
  views_short: "views",
};

export type UIKey = keyof typeof en;

const hi: Record<UIKey, string> = {
  tagline: "कुछ करने से पहले, चलिए जाँच लें।",
  login_title: "लॉग इन करें",
  username: "लॉगिन ID / यूज़रनेम",
  password: "PIN / पासवर्ड",
  new_user: "नए हैं?",
  new_user_sub: "अपने नाम और 4 अंकों के PIN से अपना अकाउंट बनाएँ। यह ख़ाली शुरू होता है — कोई डेमो डेटा नहीं।",
  create_account: "अकाउंट बनाएँ",
  signup_title: "अपना अकाउंट बनाएँ",
  signup_sub: "बस आपका नाम और 4 अंकों का PIN। कोई फ़ोन नंबर, ईमेल, आधार या बैंक जानकारी नहीं।",
  your_name: "आपका नाम",
  choose_pin: "4 अंकों का PIN चुनें",
  confirm_pin: "PIN दोबारा लिखें",
  signup_need_name: "कृपया अपना नाम लिखें।",
  signup_need_pin: "PIN ठीक 4 अंकों का होना चाहिए।",
  signup_pin_mismatch: "दोनों PIN मेल नहीं खाते।",
  signup_done_title: "अकाउंट बन गया",
  signup_done_sub: "अगली बार किसी भी फ़ोन पर इसी लॉगिन ID और अपने PIN से लॉग इन करें।",
  your_login_id: "आपकी लॉगिन ID",
  copy_id: "लॉगिन ID कॉपी करें",
  copied: "कॉपी हो गया",
  signup_write_down: "अपनी लॉगिन ID लिखकर रख लें। हम अकाउंट सेव नहीं करते, इसलिए ID या PIN भूलने पर वापस नहीं मिल सकती।",
  continue: "आगे बढ़ें",
  slow_down: "बहुत ज़्यादा कोशिशें। एक मिनट रुकें।",
  signup_privacy: "आपकी जाँचें और ट्रेड इसी फ़ोन में रहते हैं। हम यूज़र्स की कोई सूची नहीं रखते।",
  login_btn: "लॉग इन",
  login_fail: "यूज़रनेम या पासवर्ड ग़लत है।",
  demo_accounts: "डेमो अकाउंट (जजों के लिए)",
  use_this: "यह अकाउंट इस्तेमाल करें",
  privacy_line: "हम कभी आपका ब्रोकर लॉगिन, बैंक जानकारी या आधार नहीं माँगते। आपकी जाँचें इसी फ़ोन में रहती हैं।",
  nav_home: "होम",
  nav_history: "इतिहास",
  nav_learn: "सीखें",
  nav_profile: "प्रोफ़ाइल",
  nav_ask: "पूछें",
  tab_alerts: "चेतावनी",
  tab_words: "शब्द",
  all: "सभी",
  alerts_sub: "आधिकारिक स्रोतों और भरोसेमंद ख़बरों से असली धोखाधड़ी के मामले, और सरकार ने क्या इंतज़ाम किए हैं। कोई आप पर आज़माए, उससे पहले तरीके पहचानना सीखें।",
  alerts_govt: "सरकार क्या कर रही है",
  alerts_recent: "हाल की धोखाधड़ी की चेतावनियाँ",
  alerts_none: "अभी लाइव चेतावनियाँ लोड नहीं हो पाईं। ऊपर दिए सरकारी इंतज़ाम हमेशा उपलब्ध हैं।",
  alerts_note: "ख़बरें SEBI और जाने-माने न्यूज़ स्रोतों से, लगभग हर घंटे अपडेट। पूरी ख़बर के लिए स्रोत खोलें।",
  alert_official: "आधिकारिक",
  alert_news: "ख़बर",
  alert_govt: "सरकारी कार्रवाई",
  alert_translated: "अनुवाद",
  alert_read: "स्रोत पढ़ें",
  alert_open_official: "आधिकारिक साइट खोलें",
  home_alert_title: "धोखाधड़ी की चेतावनी",
  home_alert_more: "सभी चेतावनियाँ देखें",
  related_alerts: "ख़बरों में ऐसे ही धोखे",
  call_1930: "1930 पर कॉल करें",
  ask_title: "साथी से पूछें",
  ask_sub: "ऐप कैसे चलाएँ, किसी शब्द का मतलब, या धोखे कैसे होते हैं — पूछें। हिंदी या अंग्रेज़ी में लिखें या बोलें।",
  ask_rule: "साथी बातें समझाता है। यह कभी ख़रीदने-बेचने को नहीं कहता और न दाम की भविष्यवाणी करता है।",
  ask_hello: "नमस्ते! मैं साथी हूँ। आप क्या जानना चाहते हैं?",
  ask_try: "नीचे कोई सवाल दबाएँ या अपना सवाल लिखें।",
  ask_placeholder: "अपना सवाल लिखें…",
  ask_send: "भेजें",
  ask_thinking: "साथी लिख रहा है…",
  ask_clear: "चैट मिटाएँ",
  ask_src_ai: "AI जवाब, ऐप की मदद से",
  ask_src_rule: "तय सुरक्षा नियम",
  ask_src_faq: "ऐप की मदद से",
  ask_src_lookup: "SEBI सूची में खोज",
  hello: "नमस्ते",
  home_ask: "कोई शेयर ख़रीदने या बेचने की सोच रहे हैं?",
  home_ask_sub: "2 मिनट लगाकर जाँच लें — टिप, भेजने वाला, और आपके अपने हाल के ट्रेड।",
  check_btn: "फ़ैसला जाँचें",
  upload_btn: "स्क्रीनशॉट डालें",
  speak_btn: "बोलकर बताएँ",
  recent_checks: "हाल की जाँचें",
  no_checks: "अभी कोई जाँच नहीं। आपकी जाँचें यहाँ दिखेंगी।",
  paused_count: "बार आप कुछ करने से पहले रुके",
  waiting_title: "आपने रुकने का फ़ैसला किया",
  waiting_left: "बाकी",
  waiting_done: "रुकने का समय पूरा — अब ताज़ा दिमाग़ से फिर देखें।",
  followup_title: "कैसा रहा?",
  followup_sub: "एक हफ़्ते पहले आपने यह जाँचा था। पीछे मुड़कर देखने से सीख मिलती है।",
  followup_glad: "अच्छा हुआ जाँच ली",
  followup_neutral: "पता नहीं",
  followup_regret: "काश रुक जाता/जाती",
  followup_thanks: "धन्यवाद — आपके इतिहास में दर्ज हो गया।",
  step1: "आपने क्या सुना?",
  step2: "आप क्या करने वाले हैं?",
  step3: "यह ट्रेड क्यों?",
  step_of: "चरण",
  where_from: "टिप कहाँ से आई?",
  src_youtube: "YouTube",
  src_whatsapp: "WhatsApp",
  src_telegram: "Telegram",
  src_instagram: "Instagram",
  src_friend: "दोस्त / परिवार",
  src_news: "ख़बर",
  src_influencer: "फ़िनफ़्लुएंसर",
  src_sms: "SMS / कॉल",
  src_other: "कुछ और",
  know_sender: "क्या आप भेजने वाले को निजी तौर पर जानते हैं?",
  yes: "हाँ",
  no: "नहीं",
  not_sure: "पक्का नहीं",
  paste_label: "मैसेज पेस्ट करें (या जो कहा गया वह लिखें)",
  paste_ph: "जैसे: \"टाटा मोटर्स अभी ख़रीदो, 1 महीने में 40% पक्का रिटर्न!\"",
  link_label: "लिंक (YouTube / वेबसाइट / ग्रुप) — ज़रूरी नहीं",
  link_ph: "https://…",
  views_label: "व्यूज़ / फ़ॉलोअर्स (अगर दिख रहे हों) — ज़रूरी नहीं",
  add_screenshot: "स्क्रीनशॉट जोड़ें",
  reading_screenshot: "स्क्रीनशॉट से लिखावट पढ़ रहे हैं…",
  screenshot_done: "स्क्रीनशॉट से टेक्स्ट जुड़ गया। एक बार देख लें।",
  screenshot_fail: "स्क्रीनशॉट पढ़ नहीं पाए। मुख्य बातें लिख दें।",
  speak_hint: "दबाएँ और बोलें",
  listening: "सुन रहे हैं… रोकने के लिए दबाएँ",
  voice_unsupported: "इस ब्राउज़र में बोलकर लिखने की सुविधा नहीं है।",
  which_share: "कौन-सी कंपनी?",
  search_company: "कंपनी का नाम खोजें",
  search_company_all: "कोई भी NSE / BSE कंपनी खोजें (नाम या सिंबल)",
  popular_stocks: "लोकप्रिय",
  searching: "खोज रहे हैं…",
  no_company_found: "कोई कंपनी नहीं मिली। स्पेलिंग देखें, या \"कोई और कंपनी\" में जोड़ें।",
  other_company: "कोई और कंपनी (सूची में नहीं)",
  other_company_name: "कंपनी का नाम",
  buy: "ख़रीदना",
  sell: "बेचना",
  how_many: "कितने शेयर?",
  amount: "लगभग कितना पैसा? (₹)",
  amount_auto: "ताज़ा दाम से भरा गया है। आप बदल सकते हैं।",
  why_q: "यह ट्रेड क्यों सोच रहे हैं? (जितने सही हों, सब चुनें)",
  r_recommended: "किसी ने सलाह दी",
  r_news: "ख़बर देखी",
  r_recover_loss: "हाल का नुकसान वापस पाने के लिए",
  r_friends_buying: "दोस्त / सब ख़रीद रहे हैं",
  r_price_falling: "दाम गिरा, सस्ते में ख़रीदना",
  r_own_research: "मेरी अपनी रिसर्च",
  r_fear_missing: "मौका छूट न जाए",
  reason_more: "कुछ और? (ज़रूरी नहीं)",
  next: "आगे",
  back: "पीछे",
  check_now: "अभी जाँचें",
  checking: "जाँच हो रही है…",
  checking_steps: "मैसेज पढ़ रहे हैं · SEBI रिकॉर्ड देख रहे हैं · कंपनी की जानकारी · आपके हाल के ट्रेड",
  error_generic: "कुछ गड़बड़ हुई। फिर से कोशिश करें।",
  error_offline: "इंटरनेट नहीं है। इंटरनेट जोड़कर फिर कोशिश करें।",
  need_company: "कृपया कंपनी चुनें।",
  need_qty: "कृपया शेयरों की संख्या लिखें।",
  verdict_green: "कोई बड़ा ख़तरे का संकेत नहीं",
  verdict_orange: "फ़ैसले से पहले देख लें",
  verdict_red: "रुकें",
  green_note: "इसका मतलब यह नहीं कि यह अच्छा निवेश है। बस इतना कि जो हमने जाँचा, उसमें बड़े ख़तरे के संकेत नहीं मिले।",
  not_prediction: "ये ख़तरे के संकेत हैं, शेयर के भविष्य की भविष्यवाणी नहीं। फ़ैसला आपका है।",
  we_checked: "हमने जाँचीं",
  things: "चीज़ें",
  top_three: "सबसे ज़रूरी जाँच",
  tip_age_q: "यह टिप आपको कब मिली या दिखी?",
  tip_age_today: "आज",
  tip_age_week: "इस हफ़्ते",
  tip_age_month: "इस महीने",
  tip_age_older: "इससे पहले",
  tip_age_unknown: "पता नहीं",
  fresh_published: "प्रकाशित",
  fresh_fresh: "हाल की",
  fresh_weeks: "कुछ हफ़्ते पुरानी",
  fresh_months: "महीनों पुरानी",
  fresh_old: "बहुत पुरानी",
  source_name_label: "व्यक्ति या चैनल का नाम (ज़रूरी नहीं)",
  source_name_ph: "जैसे: व्यक्ति या चैनल का नाम",
  source_name_help: "हम यह नाम SEBI के रजिस्टर्ड एडवाइज़र और एनालिस्ट की सूची में खोजेंगे।",
  video_inside: "वीडियो के अंदर",
  video_watched_all: "AI ने वीडियो देखा (बोली गई बातें + स्क्रीन पर लिखा)",
  video_not_watched_short: "हम इस वीडियो के अंदर नहीं देख पाए, इसलिए सिर्फ़ टाइटल और विवरण जाँचे गए। वजह:",
  video_quota_tip: "सुझाव: मुफ़्त AI प्लान में हर मिनट और हर दिन सीमित वीडियो देखे जा सकते हैं। एक मिनट रुककर फिर जाँचें — एक बार सफल होने पर वही वीडियो याद रहता है।",
  video_nokey_tip: "सुझाव: ऐप फ़ोल्डर की .env.local फ़ाइल में GEMINI_API_KEY डालें और ऐप दोबारा चलाएँ।",
  video_watched: "AI ने पहले 15 मिनट देखे (बोली गई बातें + स्क्रीन पर लिखा)",
  video_speaker: "बोलने वाले",
  video_no_claims: "देखे गए हिस्से में कोई ख़ास दावा या कॉल नहीं मिली।",
  video_regs: "दिखाए गए SEBI नंबर",
  video_links: "बताए गए लिंक / ग्रुप / UPI",
  video_disclaimer_yes: "जोखिम की चेतावनी बोली या दिखाई गई",
  video_disclaimer_no: "कोई जोखिम चेतावनी नहीं बोली या दिखाई गई",
  video_ai_note: "AI ने पाया — समय पर टैप करके वीडियो में ख़ुद जाँचें।",
  video_not_watched: "हम इस वीडियो के अंदर नहीं देख पाए, इसलिए सिर्फ़ टाइटल और विवरण जाँचे गए। वजह नीचे \"जो हम नहीं जाँच पाए\" में है।",
  checking_video: "YouTube वीडियो देख रहे हैं (पहले 10 मिनट) — इसमें एक मिनट तक लग सकता है।",
  sec_message: "मैसेज के बारे में",
  sec_source: "भेजने वाले के बारे में",
  sec_behaviour: "आपके हाल के ट्रेड के बारे में",
  sec_company: "कंपनी के बारे में (सिर्फ़ तथ्य)",
  sec_ok: "जो ठीक लगा",
  sec_not_checked: "जो हम नहीं जाँच पाए",
  why_matters: "यह क्यों ज़रूरी है",
  what_found: "हमें क्या मिला",
  what_check: "क्या जाँचें",
  explain_term: "इसका मतलब क्या है?",
  ai_summary: "कंटेंट में क्या दावा है (AI सारांश)",
  ai_note: "कंटेंट पढ़ने में AI ने मदद की। ऊपर का रंग तय नियमों से आता है, AI से नहीं।",
  read_aloud: "सुनें",
  stop_reading: "रोकें",
  share_family: "परिवार को भेजें",
  wait_15: "15 मिनट रुकें",
  wait_day: "एक दिन सोचें (24 घंटे)",
  write_journal: "अपनी वजहें लिखें",
  i_decided: "मैंने फ़ैसला कर लिया",
  decided_go: "मैं आगे बढ़ूँगा/बढ़ूँगी",
  decided_skip: "मैं नहीं करूँगा/करूँगी",
  decision_saved: "सेव हो गया। फ़ैसला जो भी हो, आपने पहले जाँच की — बहुत अच्छा।",
  journal_title: "आपके फ़ैसले के नोट्स",
  journal_sub: "अपनी वजहें लिखने से जल्दबाज़ी का फ़ैसला धीमा होता है। बोलें या लिखें।",
  jq1: "आप यह ट्रेड क्यों करना चाहते हैं?",
  jq2: "इसके पीछे क्या सबूत है?",
  jq3: "किस बात से आपका इरादा बदल सकता है?",
  jq4: "अगर ट्रेड उल्टा पड़े, तो आप कितना नुकसान सह सकते हैं?",
  journal_save: "नोट्स सेव करें",
  journal_saved: "नोट्स सेव हो गए।",
  history_title: "आपकी जाँचें",
  learn_title: "सीखें",
  learn_sub: "आम शब्दों के आसान मतलब, और आम धोखे कैसे होते हैं।",
  learn_terms: "शब्दों के मतलब",
  learn_scams: "आम धोखे",
  how_it_works: "कैसे होता है",
  how_to_spot: "कैसे पहचानें",
  help_title: "मदद चाहिए? पैसा गया?",
  profile_title: "प्रोफ़ाइल",
  my_trades: "आपके पुराने ट्रेड",
  my_trades_sub: "सिर्फ़ घाटा-वसूली जैसी आदतें पहचानने के लिए। डेमो ट्रेड अकाउंट के साथ आते हैं; आपके जोड़े ट्रेड इसी फ़ोन में रहते हैं।",
  add_trade: "पुराना ट्रेड जोड़ें",
  import_csv: "ट्रेडबुक इम्पोर्ट करें (CSV)",
  import_done: "ट्रेड जोड़े गए",
  import_fail: "इस फ़ाइल से कोई ट्रेड नहीं पढ़ पाए। नीचे दी गई सैंपल फ़ाइल जैसा फ़ॉर्मेट इस्तेमाल करें।",
  import_excel: "यह Excel फ़ाइल है। इसे Excel में खोलें → File → Save As → \"CSV (Comma delimited)\", फिर .csv फ़ाइल इम्पोर्ट करें।",
  import_missing: "फ़ाइल में ये कॉलम नहीं मिले:",
  col_symbol: "शेयर का नाम/सिंबल",
  col_date: "तारीख़",
  col_qty: "मात्रा (शेयरों की संख्या)",
  col_price: "दाम (या कुल रकम)",
  import_skipped: "पंक्तियाँ छोड़ी गईं (तारीख़/मात्रा/दाम नहीं था)",
  import_dupes: "पहले से जुड़े थे",
  import_help: "CSV में कॉलम: तारीख़, शेयर, ख़रीद/बिक्री, मात्रा, दाम (मुनाफ़ा/नुकसान ज़रूरी नहीं)। ज़्यादातर ब्रोकर की ट्रेडबुक चल जाती है।",
  import_sample: "सैंपल CSV डाउनलोड करें",
  profit_loss: "मुनाफ़ा / नुकसान (₹)",
  date: "तारीख़",
  save: "सेव करें",
  cancel: "रद्द करें",
  delete: "हटाएँ",
  logout: "लॉग आउट",
  language: "भाषा",
  data_note: "आपका डेटा: जाँचें और जोड़े गए ट्रेड सिर्फ़ इसी ब्राउज़र में रहते हैं। हम आपके ब्रोकर या बैंक से नहीं जुड़ते।",
  sebi_list_note: "SEBI रजिस्ट्री सूची लोड",
  ai_on: "AI से पढ़ना: चालू",
  ai_off: "AI से पढ़ना: बंद (सिर्फ़ नियम)",
  install_app: "होम स्क्रीन पर जोड़ें",
  wa_share_text: "कुछ करने से पहले मैंने यह टिप संज्ञान डिसीज़न गार्ड से जाँची:",
  open_result: "खोलें",
  decision_went: "आगे बढ़े",
  decision_skipped: "छोड़ दिया",
  decision_waiting: "रुके हुए",
  usual_trade: "आम ट्रेड का साइज़",
  trades_7d: "पिछले 7 दिन में ट्रेड",
  total_trades: "दर्ज ट्रेड",
  close: "बंद करें",
  advice_reply_title: "हम ख़रीदने/बेचने की सलाह नहीं देते",
  share_received: "शेयर किया गया मैसेज मिल गया। नीचे बाकी जानकारी भरें।",
  disclaimer_footer: "यह निवेश सलाह नहीं है। यह टूल ख़तरे के संकेत जाँचता है; कभी ख़रीदने, बेचने या रखने को नहीं कहता।",
  views_short: "व्यूज़",
};

export const UI = { en, hi };
